### ISSUE TITLE
API hosted at off-spec location

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/tesk-api#48]
TESK instances are currently hosted at `https://host/v1`, but according to TES [v1.0](https://github.com/ga4gh/task-execution-schemas/blob/9e9c5aa2648d683d5574f9dbd63a025b4aea285d/openapi/task_execution_service.openapi.yaml#L64-L65) and [v1.1](https://github.com/ga4gh/task-execution-schemas/blob/117cd927aa119469ee80cedbd8940c968b81c5d6/openapi/task_execution_service.openapi.yaml#L67-L68) they should be hosted at `https://host/ga4gh/tes/v1` instead.

Surely this can be configured in Kubernetes by re-routing, but it may also be hardcoded in this repo. If so, it might be good to change it in accordance with the specs. Either way, the deployment instructions should be double-checked and modified if needed.

**Comment by lvarin** [comment]
I will take a look

**Comment by lvarin** [comment]
As far as I can see `tesk-api` already exposes its API by default in `g4agh/v1/`. Like in:
 https://csc-tesk-noauth.rahtiapp.fi/swagger-ui.html#/TaskService

The HELM chart has a different default `/v1`. I will create a small PR to `TESK` to fix this.

**Comment by uniqueg** [comment]
Perfect, thanks a lot.

Merged the PR, so closing this
